import 'package:flutter/material.dart';
import 'package:quran/quran.dart' as quran;
import 'package:quran_app/presentation/quran/quran_view.dart';

class QuranController extends State<QuranView> {
  static late QuranController instance;

  late QuranView view;
  List surahList = [];

  @override
  void initState() {
    super.initState();
    loadSurah();
  }

  void loadSurah() {
    surahList = List.generate(114, (index) {
      int surahNumber = index + 1;

      return {
        "number": surahNumber,
        "name": namaSurahIndo[surahNumber - 1],
        "latin": artiSurahIndo[surahNumber - 1],
        "totalAyat": quran.getVerseCount(surahNumber),
      };
    });

    setState(() {});
  }

  List<String> namaSurahIndo = [
    "Al-Fatihah",
    "Al-Baqarah",
    "Ali 'Imran",
    "An-Nisa'",
    "Al-Ma'idah",
    "Al-An'am",
    "Al-A'raf",
    "Al-Anfal",
    "At-Taubah",
    "Yunus",
    "Hud",
    "Yusuf",
    "Ar-Ra'd",
    "Ibrahim",
    "Al-Hijr",
    "An-Nahl",
    "Al-Isra'",
    "Al-Kahf",
    "Maryam",
    "Ta-Ha",
    "Al-Anbiya'",
    "Al-Hajj",
    "Al-Mu'minun",
    "An-Nur",
    "Al-Furqan",
    "Asy-Syu'ara'",
    "An-Naml",
    "Al-Qasas",
    "Al-'Ankabut",
    "Ar-Rum",
    "Luqman",
    "As-Sajdah",
    "Al-Ahzab",
    "Saba'",
    "Fatir",
    "Ya-Sin",
    "As-Saffat",
    "Sad",
    "Az-Zumar",
    "Ghafir",
    "Fussilat",
    "Asy-Syura",
    "Az-Zukhruf",
    "Ad-Dukhan",
    "Al-Jasiyah",
    "Al-Ahqaf",
    "Muhammad",
    "Al-Fath",
    "Al-Hujurat",
    "Qaf",
    "Az-Zariyat",
    "At-Tur",
    "An-Najm",
    "Al-Qamar",
    "Ar-Rahman",
    "Al-Waqi'ah",
    "Al-Hadid",
    "Al-Mujadilah",
    "Al-Hasyr",
    "Al-Mumtahanah",
    "As-Saff",
    "Al-Jumu'ah",
    "Al-Munafiqun",
    "At-Tagabun",
    "At-Talaq",
    "At-Tahrim",
    "Al-Mulk",
    "Al-Qalam",
    "Al-Haqqah",
    "Al-Ma'arij",
    "Nuh",
    "Al-Jinn",
    "Al-Muzzammil",
    "Al-Muddassir",
    "Al-Qiyamah",
    "Al-Insan",
    "Al-Mursalat",
    "An-Naba'",
    "An-Nazi'at",
    "'Abasa",
    "At-Takwir",
    "Al-Infitar",
    "Al-Mutaffifin",
    "Al-Insyiqaq",
    "Al-Buruj",
    "At-Tariq",
    "Al-A'la",
    "Al-Gasyiyah",
    "Al-Fajr",
    "Al-Balad",
    "Asy-Syams",
    "Al-Lail",
    "Ad-Duha",
    "Asy-Syarh",
    "At-Tin",
    "Al-'Alaq",
    "Al-Qadr",
    "Al-Bayyinah",
    "Az-Zalzalah",
    "Al-'Adiyat",
    "Al-Qari'ah",
    "At-Takasur",
    "Al-'Asr",
    "Al-Humazah",
    "Al-Fil",
    "Quraisy",
    "Al-Ma'un",
    "Al-Kausar",
    "Al-Kafirun",
    "An-Nasr",
    "Al-Lahab",
    "Al-Ikhlas",
    "Al-Falaq",
    "An-Nas",
  ];

  List<String> artiSurahIndo = [
    "Pembukaan",
    "Sapi Betina",
    "Keluarga Imran",
    "Wanita",
    "Hidangan",
    "Hewan Ternak",
    "Tempat Tertinggi",
    "Rampasan Perang",
    "Pengampunan",
    "Yunus",
    "Hud",
    "Yusuf",
    "Guruh",
    "Ibrahim",
    "Hijr",
    "Lebah",
    "Perjalanan Malam",
    "Gua",
    "Maryam",
    "طه",
    "Para Nabi",
    "Haji",
    "Orang Beriman",
    "Cahaya",
    "Pembeda",
    "Para Penyair",
    "Semut",
    "Kisah",
    "Laba-laba",
    "Romawi",
    "Luqman",
    "Sujud",
    "Golongan Bersekutu",
    "Saba'",
    "Pencipta",
    "Yasin",
    "Barisan",
    "Shad",
    "Rombongan",
    "Yang Mengampuni",
    "Dijelaskan",
    "Musyawarah",
    "Perhiasan",
    "Kabut",
    "Berlutut",
    "Bukit Pasir",
    "Muhammad",
    "Kemenangan",
    "Kamar",
    "Qaf",
    "Angin yang Menerbangkan",
    "Bukit",
    "Bintang",
    "Bulan",
    "Yang Maha Pengasih",
    "Hari Kiamat",
    "Besi",
    "Gugatan",
    "Pengusiran",
    "Wanita Diuji",
    "Barisan",
    "Jumat",
    "Orang Munafik",
    "Hari Ditampakkan Kesalahan",
    "Talak",
    "Pengharaman",
    "Kerajaan",
    "Pena",
    "Hari Kiamat",
    "Tempat Naik",
    "Nuh",
    "Jin",
    "Berselimut",
    "Berkemul",
    "Kiamat",
    "Manusia",
    "Malaikat yang Diutus",
    "Berita Besar",
    "Malaikat yang Mencabut",
    "Ia Bermuka Masam",
    "Menggulung",
    "Terbelah",
    "Orang Curang",
    "Terbelah",
    "Gugusan Bintang",
    "Yang Datang Malam",
    "Yang Paling Tinggi",
    "Hari Pembalasan",
    "Fajar",
    "Negeri",
    "Matahari",
    "Malam",
    "Waktu Dhuha",
    "Lapang",
    "Buah Tin",
    "Segumpal Darah",
    "Kemuliaan",
    "Bukti Nyata",
    "Guncangan",
    "Kuda Perang",
    "Hari Kiamat",
    "Bermegah-megahan",
    "Masa",
    "Pengumpat",
    "Gajah",
    "Quraisy",
    "Barang Berguna",
    "Nikmat Berlimpah",
    "Orang Kafir",
    "Pertolongan",
    "Api yang Bergejolak",
    "Ikhlas",
    "Waktu Subuh",
    "Manusia",
  ];

  @override
  Widget build(BuildContext context) => widget.build(context, this);
}
